@startuml
hide circle
skinparam linetype ortho

entity Student {
  * id : string <<generated>>
  --
  * name : string
  * email : string
  * department_id : string <<FK>>
}

entity Department {
  * id : string <<generated>>
  --
  * name : string
}

entity Enrollment {
  * id : string <<composite key>>
  --
  * student_id : string <<FK>>
  * course_id : string <<FK>>
  * grade : string
}

entity Course {
  * id : string <<generated>>
  --
  * name : string
  * code : string
  * credit : number
}

entity Lecturer  {
  * id : string <<generated>>
  --
  * name : string
  * email : string
  * title : string
  * department_id : <<FK>>
}

Student }|--|| Department : "belongs to"
Student ||--o{ Enrollment : "has"
Enrollment }|--|| Course : "takes"
Lecturer }|--|{ Course : "teaches/is taught to"
Lecturer }|--|| Department : "belongs to"
@enduml